# Generated by Django 5.0.3 on 2024-04-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('0', 'مُعلق'), ('1', 'تم الرفض'), ('2', 'تم الوافقة')], max_length=10),
        ),
    ]
