# Generated by Django 5.0.3 on 2024-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_vacation_substitute_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='substitute_employee',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
