# Generated by Django 5.0.3 on 2024-04-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_vacation_substitute_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['-request_date']},
        ),
    ]
