# Generated by Django 5.0.3 on 2024-04-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_vacation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={},
        ),
    ]
