# Generated by Django 5.0.3 on 2024-05-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_vacation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
