# Generated by Django 5.0.3 on 2024-06-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trust',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vacation1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='vacation1_balance',
            field=models.IntegerField(default=0),
        ),
    ]
