# Generated by Django 5.0.3 on 2024-06-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_is_trust_alter_user_phone_alter_user_vacation1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_trust',
            new_name='is_verified',
        ),
    ]
